"""Generate human-readable narrative report and behavioral CLAUDE.md snippet from profile."""

from __future__ import annotations

import json
from pathlib import Path

from rich.console import Console

from .profile import PsycheProfile

console = Console()

DOMAIN_NAMES = {
    "N": "Neuroticism",
    "E": "Extraversion",
    "O": "Openness to Experience",
    "A": "Agreeableness",
    "C": "Conscientiousness",
}


def generate_claude_md_snippet(profile: PsycheProfile) -> str:
    """Generate a behavioral-specification CLAUDE.md snippet (~400-600 words).

    Instead of trait labels ("High Openness"), this generates concrete behavioral
    if-then patterns that actually shift Claude's output.
    """
    sections: list[str] = []
    sections.append("# Personality Context (Behavioral Specification)")
    sections.append("")
    sections.append("Generated by Psyche framework. Each line is a concrete behavioral pattern, not a trait label.")
    sections.append("")

    # ── Communication Preferences ──
    comm: list[str] = []
    d = profile.big_five.domains
    a = d.get("A")
    o = d.get("O")
    n = d.get("N")
    c = d.get("C")
    e = d.get("E")

    if a and a.final_score < 40:
        comm.append("- Wants direct answers, not hedged suggestions")
        comm.append("- Prefers blunt feedback — skip diplomatic softening")
    elif a and a.final_score >= 65:
        comm.append("- Frame disagreements constructively; values harmony")

    if o and o.final_score >= 60:
        comm.append("- Prefers exploring alternatives before converging on a solution")
        comm.append("- Comfortable with long responses when depth is warranted")

    if c and c.final_score >= 60:
        comm.append("- Explain WHY, not just WHAT — rejects instructions without rationale")

    if profile.social.self_monitoring is not None:
        if profile.social.self_monitoring < 40:
            comm.append("- Consistent across contexts; what you see is what you get")
        elif profile.social.self_monitoring >= 65:
            comm.append("- Adapts communication style to context; mirror their register")

    if n and n.final_score < 35:
        comm.append("- Skip unnecessary caveats and disclaimers")
    elif n and n.final_score >= 65:
        comm.append("- Provide reassurance on ambiguous situations; show progress indicators")

    if comm:
        sections.append("## Communication Preferences")
        sections.append("")
        sections.extend(comm)
        sections.append("")

    # ── Decision-Making Style ──
    dec: list[str] = []
    if profile.social.loc_internal is not None and profile.social.loc_external is not None:
        if profile.social.loc_internal > profile.social.loc_external:
            dec.append("- Attributes outcomes to own actions; prefers proactive over reactive approaches")
        else:
            dec.append("- Aware of external constraints; factor in environmental limitations")

    if profile.emotion_reg.reappraisal is not None and profile.emotion_reg.reappraisal >= 60:
        dec.append("- Reframes setbacks as learning opportunities; responds to problems with 'what can I learn' not 'why did this happen'")

    if profile.grit.perseverance is not None and profile.grit.interest_consistency is not None:
        if profile.grit.perseverance >= 60 and profile.grit.interest_consistency < 40:
            dec.append("- Stubborn persistence during engagement but cycles between interests; expect topic pivots")
        elif profile.grit.perseverance >= 60 and profile.grit.interest_consistency >= 60:
            dec.append("- Sustained, persistent focus on long-term goals")

    if n and n.final_score >= 55:
        dec.append("- Needs to verbalize tradeoffs before committing; let them think out loud")

    if dec:
        sections.append("## Decision-Making Style")
        sections.append("")
        sections.extend(dec)
        sections.append("")

    # ── Feedback & Conflict ──
    conf: list[str] = []
    if a and a.final_score < 40:
        conf.append("- Prefers honest pushback over diplomatic agreement")
        conf.append("- Reacts negatively to condescension, even mild forms")

    # Feedback & disagreement directives — scoped to text-turn behavior only.
    # Removed anti-patterns: 'withdrawal != rejection', 'check in if they go
    # quiet', 'seeks reassurance after criticism' as bare observations —
    # these assume state Claude Code cannot observe in a turn-based text
    # channel. See narrative_llm.ANTI_PATTERN_PHRASES for the guardrail.
    if profile.attachment.anxiety is not None and profile.attachment.anxiety >= 60:
        conf.append(
            "- When the user asks whether a change is correct a second time, "
            "answer the same question the same way rather than hedging more "
            "— repeated asking reflects calibration need, not a request for "
            "more caveats"
        )

    if profile.emotion_reg.reappraisal is not None and profile.emotion_reg.reappraisal >= 60:
        conf.append(
            "- Reframing-based suggestions ('here's another way to think about "
            "this') land better than direct prescription for ambiguous problems"
        )

    if profile.hexaco.honesty_humility is not None and profile.hexaco.honesty_humility >= 65:
        conf.append("- Low tolerance for manipulation or social games; values straightforwardness")

    if conf:
        sections.append("## Feedback & Conflict")
        sections.append("")
        sections.extend(conf)
        sections.append("")

    # ── Motivation Structure ──
    mot: list[str] = []
    if profile.needs.autonomy is not None and profile.needs.autonomy >= 60:
        mot.append("- Driven by autonomous exploration, not external directives")
    if profile.needs.competence is not None and profile.needs.competence >= 60:
        mot.append("- Motivated by mastery; responds to challenges that stretch capability")

    # RIASEC top types
    riasec_scores = {
        "Investigative": profile.vocational.investigative,
        "Artistic": profile.vocational.artistic,
        "Social": profile.vocational.social,
        "Enterprising": profile.vocational.enterprising,
        "Realistic": profile.vocational.realistic,
        "Conventional": profile.vocational.conventional,
    }
    top_types = sorted(
        [(k, v) for k, v in riasec_scores.items() if v is not None],
        key=lambda x: x[1],
        reverse=True,
    )[:2]
    if top_types:
        type_str = " + ".join(t[0] for t in top_types)
        mot.append(f"- Vocational orientation: {type_str} — use analogies from these domains")

    if profile.grit.interest_consistency is not None and profile.grit.interest_consistency < 40:
        mot.append("- Interest cycles through topics; sustained engagement requires the field to move fast enough to stay ahead of the learning curve")

    if mot:
        sections.append("## Motivation Structure")
        sections.append("")
        sections.extend(mot)
        sections.append("")

    # ── Epistemic Style ──
    epi: list[str] = []
    if profile.cognitive.crt_score is not None and profile.cognitive.crt_score >= 6:
        epi.append(f"- Analytical (CRT {profile.cognitive.crt_score:.0f}/7) — prefers rigorous reasoning")
    if profile.cognitive.need_for_cognition is not None and profile.cognitive.need_for_cognition >= 65:
        epi.append("- High need for cognition; enjoys complexity for its own sake")

    if o and o.final_score >= 60:
        epi.append("- Builds conceptual frameworks rapidly; maps new information onto existing structures")

    epi.append("- High tolerance for 'I don't know'; very low tolerance for confident-sounding guesses")
    epi.append("- Prefers probabilistic framing over categorical claims")

    if epi:
        sections.append("## Epistemic Style")
        sections.append("")
        sections.extend(epi)
        sections.append("")

    # ── When other people come up in conversation ──
    # Scoped to directives Claude Code can actually apply when the user
    # describes another person or asks advice about a relationship/team.
    # Removed anti-patterns: "Comfortable with silence" (silence not
    # observable), "Gets overwhelmed by others' strong emotions" (not a
    # coding-agent concern), bare trait labels about empathy modes.
    inter: list[str] = []
    if profile.empathy.empathic_concern is not None and profile.empathy.perspective_taking is not None:
        pt = profile.empathy.perspective_taking
        ec = profile.empathy.empathic_concern
        pd = profile.empathy.personal_distress
        if pt >= 60 and ec <= 55 and (pd is None or pd < 45):
            inter.append(
                "- When the user describes another person's behavior as "
                "irrational or confusing, do not amplify that framing — "
                "offer a model-building framing instead (what goal, "
                "constraint, or incentive would make this behavior locally "
                "rational?). He reaches for simulation-based perspective-"
                "taking first and it alienates him; a model handshakes better"
            )

    if inter:
        sections.append("## When Other People Come Up")
        sections.append("")
        sections.extend(inter)
        sections.append("")

    # ── Methods note ──
    methods = ", ".join(profile.metadata.methods_used) if profile.metadata.methods_used else "pending"
    inst_count = len(profile.manifest.instruments) if profile.manifest.instruments else 17
    tier_note = f" ({profile.manifest.tier} tier)" if profile.manifest.tier else ""
    sections.append(f"*Based on: {methods}. Behavioral predictions derived from extended psychometric battery ({inst_count} instruments{tier_note}) + corpus analysis.*")

    return "\n".join(sections)


def generate_narrative_report(
    profile: PsycheProfile,
    interview_transcript: str | None = None,
) -> str:
    """Prepare data for narrative report generation.

    The actual narrative is best generated by Claude Code (via Task subagent)
    which can read all source files and produce flowing prose. This function:
    1. Writes a structured profile summary to profiles/narrative-input.md
    2. Returns the existing report.md if available (preserving prior narrative)
    3. Returns a placeholder if no prior narrative exists

    To regenerate the narrative, run from Claude Code:
        Task(general-purpose): "Read profiles/narrative-input.md, interview data,
        and source files, then write a 2000-4000 word narrative to profiles/report.md"
    """
    # Build and save the structured data summary for LLM consumption
    profile_data = _build_profile_summary(profile)

    project_root = Path(__file__).parent.parent.parent.parent
    input_path = project_root / "profiles" / "narrative-input.md"
    input_path.parent.mkdir(parents=True, exist_ok=True)

    input_content = f"""# Narrative Report Input Data

This file is auto-generated by `psyche synthesize`. Feed it to Claude Code
(via Task subagent) along with interview transcript and corpus evidence
to generate the narrative report.

{profile_data}
"""
    if interview_transcript:
        input_content += f"""
## INTERVIEW TRANSCRIPT (for evidence quotes)

{interview_transcript[:8000]}
"""

    input_path.write_text(input_content)
    console.print(f"  Narrative input saved to {input_path}")

    # Return existing report if available (don't overwrite good narratives)
    report_path = project_root / "profiles" / "report.md"
    if report_path.exists():
        existing = report_path.read_text()
        if len(existing.split()) > 500:
            console.print(f"  Existing narrative preserved ({len(existing.split())} words)")
            console.print("  To regenerate: use Claude Code Task subagent with profiles/narrative-input.md")
            return existing

    console.print("  [yellow]No existing narrative. Generate via Claude Code Task subagent.[/yellow]")
    console.print("  Input data saved to profiles/narrative-input.md")
    return f"*Narrative pending. Run generation via Claude Code using profiles/narrative-input.md as input.*"


def _build_profile_summary(profile: PsycheProfile) -> str:
    """Build a structured text summary of all profile data for the LLM."""
    lines: list[str] = []

    lines.append("## BIG FIVE (multi-method merged)")
    for key in ["O", "C", "E", "A", "N"]:
        trait = profile.big_five.domains.get(key)
        if not trait:
            continue
        name = DOMAIN_NAMES[key]
        lines.append(f"\n### {name}: {trait.final_score:.0f}/100 (CI: {trait.ci_lower:.0f}-{trait.ci_upper:.0f}, divergence={trait.divergence:.1f})")
        for est in trait.estimates:
            ev_str = "; ".join(f'"{e}"' for e in est.evidence[:2]) if est.evidence else "no quotes"
            lines.append(f"  {est.method}: {est.score:.0f} ({est.confidence}) — {ev_str}")

    # Facet comparison
    if profile.big_five.facet_scores:
        # Build dynamic header showing which NEO instruments contributed
        neo_sources: list[str] = []
        sample_fs = profile.big_five.facet_scores[0] if profile.big_five.facet_scores else None
        if sample_fs:
            if sample_fs.neo60 is not None or any(fs.neo60 is not None for fs in profile.big_five.facet_scores):
                neo_sources.append("NEO-60 = 2 items/facet")
            if any(fs.neo120 is not None for fs in profile.big_five.facet_scores):
                neo_sources.append("NEO-120 = 4 items/facet")
            if any(fs.neo300 is not None for fs in profile.big_five.facet_scores):
                neo_sources.append("NEO-300 = 10 items/facet")
            if any(fs.cat is not None for fs in profile.big_five.facet_scores):
                neo_sources.append("CAT = adaptive IRT")
        header = ", ".join(neo_sources) if neo_sources else "NEO-120, NEO-300"
        lines.append(f"\n## NEO FACET COMPARISON ({header})")
        current_domain = ""
        for fs in profile.big_five.facet_scores:
            if fs.domain != current_domain:
                current_domain = fs.domain
                domain_name = DOMAIN_NAMES.get(current_domain, current_domain)
                lines.append(f"\n  {domain_name} facets:")
            cols: list[str] = []
            if any(f.neo60 is not None for f in profile.big_five.facet_scores):
                n60 = f"{fs.neo60:.0f}" if fs.neo60 is not None else "—"
                cols.append(f"NEO-60: {n60:>3s}")
            if any(f.neo120 is not None for f in profile.big_five.facet_scores):
                n120 = f"{fs.neo120:.0f}" if fs.neo120 is not None else "—"
                cols.append(f"NEO-120: {n120:>3s}")
            if any(f.neo300 is not None for f in profile.big_five.facet_scores):
                n300 = f"{fs.neo300:.0f}" if fs.neo300 is not None else "—"
                cols.append(f"NEO-300: {n300:>3s}")
            if any(f.cat is not None for f in profile.big_five.facet_scores):
                cat = f"{fs.cat:.0f}" if fs.cat is not None else "—"
                cat_se = f" (SE={fs.cat_se:.2f})" if fs.cat_se is not None else ""
                cols.append(f"CAT: {cat:>3s}{cat_se}")
            avg = f"{fs.average:.0f}" if fs.average is not None else "—"
            cols.append(f"avg: {avg:>3s}")
            lines.append(f"    {fs.name:25s}  {'  '.join(cols)}")

    # HEXACO — adapt to instrument version
    hexaco_version = "HEXACO-200" if profile.hexaco.facets else "HEXACO-60"
    lines.append(f"\n## {hexaco_version} (6-factor model, convergent validity check)")
    hexaco_map = {
        "honesty_humility": "Honesty-Humility (UNIQUE — not in Big Five)",
        "emotionality": "Emotionality (cf. Neuroticism)",
        "extraversion": "Extraversion (cf. Big Five E)",
        "agreeableness": "Agreeableness (cf. Big Five A)",
        "conscientiousness": "Conscientiousness (cf. Big Five C)",
        "openness": "Openness (cf. Big Five O)",
    }
    for field, label in hexaco_map.items():
        val = getattr(profile.hexaco, field)
        if val is not None:
            lines.append(f"  {label}: {val:.0f}/100")
    if profile.hexaco.facets:
        lines.append("\n  HEXACO-200 Facets:")
        for facet_id, score in sorted(profile.hexaco.facets.items()):
            lines.append(f"    {facet_id}: {score:.0f}/100")

    # Values
    if profile.values.values:
        lines.append("\n## VALUES (Schwartz framework)")
        lines.append(f"  Top 3: {', '.join(profile.values.top_3)}")
        lines.append(f"  Bottom 3: {', '.join(profile.values.bottom_3)}")
        for k, v in sorted(profile.values.values.items(), key=lambda x: x[1].final_score, reverse=True):
            ev = "; ".join(f'"{e}"' for e in v.estimates[0].evidence[:1]) if v.estimates and v.estimates[0].evidence else ""
            lines.append(f"  {k}: {v.final_score:.0f}/100 {ev}")

    # Cognitive
    lines.append("\n## COGNITIVE")
    if profile.cognitive.crt_score is not None:
        lines.append(f"  CRT: {profile.cognitive.crt_score:.0f}/7")
    if profile.cognitive.need_for_cognition is not None:
        lines.append(f"  Need for Cognition: {profile.cognitive.need_for_cognition:.0f}/100")
    if profile.cognitive.self_esteem is not None:
        lines.append(f"  Self-Esteem (Rosenberg): {profile.cognitive.self_esteem:.0f}/100")

    # Dark Triad
    lines.append("\n## DARK TRIAD (SD3)")
    if profile.dark_triad.machiavellianism is not None:
        lines.append(f"  Machiavellianism: {profile.dark_triad.machiavellianism:.0f}/100")
    if profile.dark_triad.narcissism is not None:
        lines.append(f"  Narcissism: {profile.dark_triad.narcissism:.0f}/100")
    if profile.dark_triad.psychopathy is not None:
        lines.append(f"  Psychopathy: {profile.dark_triad.psychopathy:.0f}/100")

    # Extended Battery
    lines.append("\n## ATTACHMENT (ECR-R)")
    lines.append(f"  Anxiety: {profile.attachment.anxiety}/100")
    lines.append(f"  Avoidance: {profile.attachment.avoidance}/100")

    lines.append("\n## EMOTION REGULATION (ERQ)")
    lines.append(f"  Cognitive Reappraisal: {profile.emotion_reg.reappraisal}/100")
    lines.append(f"  Expressive Suppression: {profile.emotion_reg.suppression}/100")

    lines.append("\n## EMPATHY (IRI)")
    lines.append(f"  Fantasy: {profile.empathy.fantasy}/100")
    lines.append(f"  Perspective Taking: {profile.empathy.perspective_taking}/100")
    lines.append(f"  Empathic Concern: {profile.empathy.empathic_concern}/100")
    lines.append(f"  Personal Distress: {profile.empathy.personal_distress}/100")

    lines.append(f"\n## SELF-MONITORING: {profile.social.self_monitoring}/100")
    # LOC — adapt to 2-dimensional (IE-4) or 3-dimensional (Levenson IPC)
    if profile.social.loc_powerful_others is not None or profile.social.loc_chance is not None:
        lines.append(f"\n## LOCUS OF CONTROL (Levenson IPC-24)")
        lines.append(f"  Internal: {profile.social.loc_internal}/100")
        lines.append(f"  Powerful Others: {profile.social.loc_powerful_others}/100")
        lines.append(f"  Chance: {profile.social.loc_chance}/100")
    else:
        lines.append(f"\n## LOCUS OF CONTROL (IE-4)")
        lines.append(f"  Internal: {profile.social.loc_internal}/100")
        lines.append(f"  External: {profile.social.loc_external}/100")

    grit_version = "Grit-O" if profile.grit.overall is not None else "Grit-S"
    lines.append(f"\n## GRIT ({grit_version})")
    lines.append(f"  Perseverance of Effort: {profile.grit.perseverance}/100")
    lines.append(f"  Consistency of Interest: {profile.grit.interest_consistency}/100")
    if profile.grit.overall is not None:
        lines.append(f"  Overall Grit: {profile.grit.overall}/100")

    lines.append(f"\n## VOCATIONAL INTERESTS (RIASEC)")
    for field in ("realistic", "investigative", "artistic", "social", "enterprising", "conventional"):
        val = getattr(profile.vocational, field)
        lines.append(f"  {field.capitalize()}: {val}/100")

    bpns_version = "BPNS-21" if profile.needs.autonomy_frustration is not None else "BPNS-9"
    lines.append(f"\n## BASIC NEEDS ({bpns_version})")
    lines.append(f"  Autonomy: {profile.needs.autonomy}/100")
    lines.append(f"  Competence: {profile.needs.competence}/100")
    lines.append(f"  Relatedness: {profile.needs.relatedness}/100")
    if profile.needs.autonomy_frustration is not None:
        lines.append(f"  Autonomy Frustration: {profile.needs.autonomy_frustration}/100")
        lines.append(f"  Competence Frustration: {profile.needs.competence_frustration}/100")
        lines.append(f"  Relatedness Frustration: {profile.needs.relatedness_frustration}/100")

    lines.append(f"\n## CLINICAL SCREENS")
    lines.append(f"  PHQ-9 (Depression): {profile.clinical.phq9}/27 — {profile.clinical.phq9_severity}")
    lines.append(f"  GAD-7 (Anxiety): {profile.clinical.gad7}/21 — {profile.clinical.gad7_severity}")

    # Persona model
    lines.append("\n## PERSONA MODEL (behavioral predictions)")
    persona = profile.persona
    lines.append(f"  Communication: {persona.communication.directness}; {persona.communication.depth_preference}")
    lines.append(f"  Audience: {persona.communication.audience_adaptation}")
    lines.append(f"  Decision: {persona.decision_making.attribution_style}; {persona.decision_making.deliberation_style}")
    lines.append(f"  Risk: {persona.decision_making.risk_orientation}")
    lines.append(f"  Conflict: {persona.conflict_response.under_criticism}")
    lines.append(f"  Regulation: {persona.conflict_response.regulation_strategy}")
    lines.append(f"  Empathy: {persona.interpersonal.empathy_mode}")
    lines.append(f"  Ethics: {persona.interpersonal.ethical_stance}")
    lines.append(f"  Motivation: needs={persona.motivation.primary_needs}, domains={persona.motivation.domain_preferences}")
    lines.append(f"  Persistence: {persona.motivation.persistence_pattern}")
    lines.append(f"  Interest: {persona.motivation.interest_consistency}")

    if persona.characteristic_phrases:
        lines.append("\n## CHARACTERISTIC PHRASES (from interview)")
        for phrase in persona.characteristic_phrases[:8]:
            lines.append(f'  "{phrase}"')

    lines.append(f"\n## METADATA")
    lines.append(f"  Methods: {', '.join(profile.metadata.methods_used)}")
    lines.append(f"  Corpus: {profile.metadata.corpus_word_count:,} words from {', '.join(profile.metadata.corpus_sources)}")
    # Dynamic instrument count from manifest
    if profile.manifest.instruments:
        inst_count = len(profile.manifest.instruments)
        inst_names = ", ".join(r.instrument_id for r in profile.manifest.instruments)
        lines.append(f"  Tier: {profile.manifest.tier}")
        lines.append(f"  Instruments: {inst_count} ({inst_names})")
    else:
        lines.append(f"  Instruments: (manifest not populated)")

    return "\n".join(lines)


