"""Parser for academic writing samples (Markdown files with frontmatter)."""

from __future__ import annotations

import hashlib
import os
import re
from datetime import datetime
from pathlib import Path

from .types import TextSample


# Files known to be AI-generated content, not the user's own writing.
# These are ChatGPT/Claude drafts saved as docs, identifiable by:
# - Opening with AI-assistant phrasing ("Got it!", "Below is a", "Great, I will")
# - Large word counts with no personal voice
# - Subject matter generated on request (history narratives, medical summaries)
AI_GENERATED_PREFIXES = [
    "Got it!",
    "Below is a",
    "Great, I will",
    "Here is",
    "Here's a",
    "I'll develop",
    "Develop ",
    "Sure!",
    "Absolutely!",
    "Of course!",
    "Let me ",
    "I'll ",
]

# Files identified as AI-generated by manual review
# (content was generated by ChatGPT/Claude on request)
AI_GENERATED_FILES = {
    "Docs_-_NAFLD.md",  # AI-generated medical research summary
}

# Files that are templates, legal docs, or others' writing
EXCLUDE_PATTERNS = [
    "Certificate_of_Incumbency",
    "Sample_of_Document",
]


def _is_ai_generated(body: str) -> bool:
    """Heuristic: check if text body was generated by an AI assistant."""
    first_200 = body[:200].strip()
    return any(first_200.startswith(prefix) for prefix in AI_GENERATED_PREFIXES)


def _self_name_parts() -> set[str]:
    """Lowercased name fragments identifying the author (from PSYCHE_SELF_NAMES).

    Real names are intentionally not hardcoded in this public repo.
    """
    parts: set[str] = set()
    for name in os.environ.get("PSYCHE_SELF_NAMES", "").split(","):
        for part in name.strip().lower().split():
            if part:
                parts.add(part)
    return parts


def _body_author_mismatch(body: str) -> bool:
    """Check if body text attributes authorship to someone other than the author."""
    self_parts = _self_name_parts()
    if not self_parts:
        return False  # cannot determine mismatch without configured self names
    # Look for "By: <Name>" patterns in the first 500 chars
    first_500 = body[:500]
    match = re.search(r"(?:By|by|BY)[:\s]+([A-Z][a-z]+ [A-Z][a-z]+)", first_500)
    if match:
        name = match.group(1).lower()
        if not any(part in name for part in self_parts):
            return True
    return False


def _extract_author(frontmatter: str) -> str | None:
    """Extract author from frontmatter."""
    for line in frontmatter.split("\n"):
        line = line.strip()
        if line.startswith("author:"):
            return line.split(":", 1)[1].strip().strip("'\"")
    return None


def _is_self_authored(author: str | None, filename: str) -> bool:
    """Check if the file is authored by the user."""
    if author is None:
        return True  # Assume self if no author specified

    author_lower = author.lower()
    # Accept variations of the user's name (from PSYCHE_SELF_NAMES; real names
    # are intentionally not hardcoded in this public repo)
    self_parts = _self_name_parts()
    if not self_parts:
        return True  # cannot verify without configured self names; assume self
    return any(part in author_lower for part in self_parts)


def parse_academic(directory: Path) -> list[TextSample]:
    """Parse academic writing markdown files into TextSamples.

    Filters:
    - Skips files < 50 words (fragments)
    - Skips AI-generated content (ChatGPT/Claude drafts saved as docs)
    - Skips legal templates and non-writing documents
    - Skips files authored by others (per PSYCHE_SELF_NAMES)
    """
    samples: list[TextSample] = []
    filtered_count = 0

    for md_file in sorted(directory.glob("*.md")):
        # Check exclusion patterns
        if any(pat in md_file.name for pat in EXCLUDE_PATTERNS):
            filtered_count += 1
            continue

        # Check known AI-generated files
        if md_file.name in AI_GENERATED_FILES:
            filtered_count += 1
            continue

        content = md_file.read_text(encoding="utf-8")

        # Split frontmatter and body
        body = content
        ts: datetime | None = None
        author: str | None = None

        if content.startswith("---"):
            parts = content.split("---", 2)
            if len(parts) >= 3:
                frontmatter = parts[1]
                body = parts[2].strip()
                author = _extract_author(frontmatter)

                for line in frontmatter.split("\n"):
                    line = line.strip()
                    if line.startswith("created:"):
                        date_str = line.split(":", 1)[1].strip().strip("'\"")
                        try:
                            ts = datetime.fromisoformat(date_str)
                        except ValueError:
                            pass

        # Filter: too short
        if not body or len(body.split()) < 50:
            filtered_count += 1
            continue

        # Filter: not self-authored
        if not _is_self_authored(author, md_file.name):
            filtered_count += 1
            continue

        # Filter: AI-generated content
        if _is_ai_generated(body):
            filtered_count += 1
            continue

        # Filter: body attributes authorship to someone else
        if _body_author_mismatch(body):
            filtered_count += 1
            continue

        file_id = hashlib.sha256(md_file.name.encode()).hexdigest()[:12]

        samples.append(
            TextSample(
                id=f"academic-{file_id}",
                source="academic",
                author="self",
                timestamp=ts,
                text=body,
            )
        )

    return samples
